### ISSUE TITLE
ValueError: too many values to unpack

### ISSUE THREAD

**Issue by Sugaretto** [MyBook/zabbix-exporter#10]
Hi, when I run the zabbix_exporter and open the metrics via browser I get the following error in the console:

`Exporting Zabbix metrics on http://0.0.0.0:9224`
`[2019-06-05 09:10:15] Fetch failed`
`Traceback (most recent call last):`
`  File "/usr/local/lib/python2.7/dist-packages/zabbix_exporter/core.py", line 147, in do_GET
    response = generate_latest(REGISTRY) + generate_latest(exporter_registry)`
`  File "/usr/local/lib/python2.7/dist-packages/zabbix_exporter/prometheus.py", line 38, in generate_latest`
`    name, labels, value, timestamp = sample`
`ValueError: too many values to unpack`

I'm not understanding the root cause, if it depends from the amount of date that the exporter is taking or I need to customize the config yml file.

Thanks for your help!

**Comment by Sugaretto** [comment]
### @coagulant : This problem is related to who this exporter has been written. In particular seems it's only able to take metric composed by 3 or maximum 4 parameters (name, labels, value, timestamp).
My zabbix server is sending also metrics with 5 parameters (name, labels, value, timestamp, exemplar) so the code is not able to manage it.
I also seen that the file
/usr/local/lib/python2.7/dist-packages/zabbix_exporter/prometheus.py
is based on the prometheus client as described:

_"""Code in this module is based on prometheus client https://github.com/prometheus/client_python
   Code is vendored and forked to enable timestamps support in python client
   Copyright 2015 The Prometheus Authors
"""
**from prometheus_client import core**_

### I'f I'm not wrong the file core.py on the prometheus client repository, has been modified, so the current zabbix_exporter code is failing me with this output:
_Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/zabbix_exporter/core.py", line 149, in do_GET
    response = generate_latest(REGISTRY) + generate_latest(exporter_registry)
  File "/usr/local/lib/python2.7/dist-packages/zabbix_exporter/prometheus.py", line 53, in generate_latest
    output.append('{0}{1} {2}{3}\n'.format(name, labelstr, core._floatToGoString(value),
AttributeError: 'module' object has no attribute '_floatToGoString'_

Am I wrong?
